// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application"
import { application } from "controllers/application"

import StimulusReflex from 'stimulus_reflex'
import consumer from 'channels/consumer'
import controller from 'controllers/application_controller'
import CableReady from 'cable_ready'

import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

StimulusReflex.initialize(application, { controller, isolate: true })
application.consumer = consumer
StimulusReflex.debug = true
//if (process.env.RAILS_ENV === 'development') StimulusReflex.debug = true

CableReady.initialize({ consumer })
